# image will be published to ghcr.io/<user>/<name>
name: HyperCore
# description will be included in the image's metadata
description: An OS designed for cloud-native, hyper-converged environments, blending virtualization, storage, and compute into one seamless platform.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/ucore
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - cockpit-machines
      - xen
    remove:
      # - 
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

